instagram_scraper/urls.py
from django.urls import path, include
from instagram_scraper import views

app_name = "instagram_scraper"

urlpatterns = [
    path("get_insta/", views.get_insta, name="get_insta"),
]

instagram_scraper_project/urls.py
from django.contrib import admin
from django.urls import path, include
from instagram_scraper import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("instagram/", include("instagram_scraper.urls")),
]

instagram_scraper/models.py
from django.db import models

from datetime import datetime


class InstagramDownload(models.Model):
    link = models.CharField(max_length=200)
    caption = models.TextField(blank=True)  # Allow blank caption
    like = models.TextField(blank=True)
    # comments = models.PositiveIntegerField(default=0)
    username = models.CharField(max_length=100)
    date = models.TextField(blank=True)

    def __str__(self):
        return self.link

instagram_scraper/views.py
from django.shortcuts import render, redirect
import os, requests
from django.contrib import messages
from instalooter import looters
from instalooter.looters import InstaLooter
from instalooter.looters import PostLooter
from .models import InstagramDownload
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import time

options = Options()
options.add_argument("--headless")


def index(request):
    return render(request, "tubeloader/index.html")


def is_valid_instagram_url(url):
    try:
        response = requests.get(url)
        return response.status_code == 200 and "instagram.com" in response.url
    except Exception as e:
        print(f"Error checking URL validity: {e}")
        return False


def extract_content(url):
    driver = webdriver.Chrome(options=options)
    driver.get(url)

    # Wait for the page to load
    time.sleep(5)

    caption = driver.find_element(
        By.XPATH,
        "//div[@class='_a9zn _a9zo']/div[@class='_a9zr']/div[@class='_a9zs']/h1[@class='_ap3a _aaco _aacu _aacx _aad7 _aade']",
    ).text
    like = driver.find_element(
        By.XPATH,
        "//div[@class='x9f619 xjbqb8w x78zum5 x168nmei x13lgxp2 x5pf9jr xo71vjh xr1yuqi xkrivgy x4ii5y1 x1gryazu x1n2onr6 x1plvlek xryxfnj x1iyjqo2 x2lwn1j xeuugli xdt5ytf x1a02dak xqjyukv x1cy8zhl x1oa3qoh x1nhvcw1']",
    ).text
    username = driver.find_element(
        By.XPATH,
        "//a[@class='x1i10hfl xjbqb8w x1ejq31n xd10rxx x1sy0etr x17r0tee x972fbf xcfux6l x1qhh985 xm0m39n x9f619 x1ypdohk xt0psk2 xe8uvvx xdj266r x11i5rnm xat24cr x1mh8g0r xexx8yu x4uap5 x18d9i69 xkhd6sd x16tdsg8 x1hl2dhg xggy1nq x1a2a7pz  _acan _acao _acat _acaw _aj1- _ap30 _a6hd']",
    ).text
    date = driver.find_element(
        By.XPATH,
        "//div[@class='x1yztbdb x1h3rv7z x1swvt13']/div[@class='x9f619 xjbqb8w x78zum5 x168nmei x13lgxp2 x5pf9jr xo71vjh x1n2onr6 x1plvlek xryxfnj x1c4vz4f x2lah0s x1q0g3np xqjyukv x6s0dn4 x1oa3qoh x1nhvcw1']",
    ).text

    driver.quit()
    return caption, like, username, date


def get_insta(request):
    homedir = os.path.expanduser("~")
    dirs = homedir + "/Downloads"
    if request.method == "POST":
        link = request.POST.get("links")
        is_valid_instagram_url(link)
        caption, like, username, date = extract_content(link)

        r = InstagramDownload(
            link=link, caption=caption, like=like, username=username, date=date
        )
        r.save()

        # p = InstaLooter.get_post_info(link)
        # print(p)

        # if "get_video" in request.POST:
        #     print("if")
        #     l = "nathiyarajendiran_nathiiiii"
        #     PostLooter(l).download_videos(dirs, media_count=50)
        # elif "get_photo" in request.POST:
        #     l = "nathiyarajendiran_nathiiiii"
        #     PostLooter(1).download(dirs, media_count=50)

    return index(request)

templates/tubeloader/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <title>Instagram Media Downloader</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="">Instagram Media Downloader</a>
  </nav>

  <div class="jumbotron">
    <h1 class="display-4">Instagram Media Downloader</h1>
    <p class="lead">This is a simple Instagram Media Downloader</p>
    <hr class="my-4">

    <form method='post' action="{% url 'instagram_scraper:get_insta' %}">
      {% csrf_token %}
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Paste your link here" aria-label="Paste your link here"
          aria-describedby="button-addon4" name="links">
        <div class="input-group-append" id="button-addon4">
          <button name="get_photo" class="btn btn-dark" type="submit">Photo</button>
          <button name="get_video" class="btn btn-dark" type="submit">Video</button>
        </div>
      </div>
    </form>
  </div>



</body>

</html>

templates/tubeloader/insta.html
{% load static %}
<html>

<head>
  <title>Instagram Media Downloader</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'instagram_scraper:instavid' %}">Instagram Media Downloader</a>
  </nav>

  <div class="jumbotron">
    <h1 class="display-4">Instagram Media Downloader</h1>
    <p class="lead">This is a simple Instagram Media Downloader</p>
    <hr class="my-4">

    <form method='post' action="{% url 'instagram_scraper:get_insta' %}">
      {% csrf_token %}
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Paste your link here" aria-label="Paste your link here"
          aria-describedby="button-addon4" name="links">
        <div class="input-group-append" id="button-addon4">
          <button name="get_photo" class="btn btn-dark" type="submit">Photo</button>
          <button name="get_video" class="btn btn-dark" type="submit">Video</button>
        </div>
      </div>
    </form>
  </div>

  <h2 class="section-header text-center">How to Download Instagram Media?</h2>
  <br>
  <hr class="style-two">
  <br>
  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-lg-4 text-center">
      <img src="{% static 'cop.png' %}" width="64" height="64">
      <h2>1. Copy Post's Link</h2>
      <p>Go to Instagram, open the Post which you want to download, and copy its link.</p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4 text-center">
      <img src="{% static 'clipboard.png' %}" width="64" height="64">
      <h2>2. Paste Post's Link</h2>
      <p>Paste the post's link into the search bar at the top, and then press the Photo button if the post is a Picture
        or press the Video button if it is a Video.</p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4 text-center">
      <img src="{% static 'down.png' %}" width="64" height="64">
      <h2>3. Download Post</h2>
      <p>The Post will start Downloading.</p>
    </div><!-- /.col-lg-4 -->
  </div><!-- /.row -->
</body>

</html>